### ISSUE TITLE
complete also for nvim

### ISSUE THREAD

**Issue by ibotty** [SuperSandro2000/vim-bash-completion#2]
`complete` accepts multiple names, so adding `nvim` is enough.

**Comment by SuperSandro2000** [comment]
Does neovim has new options that would need to be added?

**Comment by ibotty** [comment]
AFAIK it uses the same netrw as vim.  It does support some other uri schemes, see `:help netrw`, but I doubt someone is using these.

**Comment by SuperSandro2000** [comment]
I have added nvim to the complete command. I also looked through the other protocols and the only interesting would be sftp. Going to create an issue to add this one later because it requires some refactoring.

**Comment by eggbean** [comment]
I always type `vi`, which opens `vim` anyway and I also alias it to `nvim` nowadays, so I added `vi` to the last line.

However, the bash completion doesn't seem to work for `nvim` or `vi` on a terminal session until I tab complete `vim`. Only after that the tab completion works for `vi` and `nvim`. I am curious to know why this is happening.

EDIT: I just noticed that it doesn't happen on a server where I have the file in `etc/bash_completion.d/`, but it does happen in my laptop where I have it in `~/.local/share/bash-completion/completions`. Strange.

**Comment by SuperSandro2000** [comment]
The file is probably lazy loaded. It should work when you add a symlink named after your binary.

**Comment by eggbean** [comment]
I actually tried that, if this is what you mean. I made symlinks to the file called `vi` and `nvim` in the `~/.local/share/bash-completion/completions` directory and it still happens. Not a big problem of course - I was just wondering what was going on.
